name: Test Output
outputs:
  sub-pkg-ver-id:
    description: >-
      Subscriber package version ID of the newly created package version, if
      created successfully.
    value: >-
      ${{ steps.step-one.outputs.sub-pkg-ver-id }}
runs: 
  using: composite
  steps:
    - name: Step One
      id: step-one
      shell: sh
      run: |

        echo "Działa"

        test_variable="tak"
        echo "$test_variable"

        pkg_create_report="$(cat <<EOF
        {
        "status": 0,
        "result": [
          {
            "PatchVersion": 0,
            "BuildNumber": 2,
            "Id": "93thui54k",
            "SubscriberPackageVersionId": "randomID",
            "AncestorVersion": "N/A"
            "BuildDurationInSeconds": "",
            "HasMetadataRemoved": "N/A",
            "CreatedBy": "32y4ui34"
          }
          ],
          "warnings": []
        }
        EOF
        )"

        echo "$pkg_create_report"

        final_variable=$(jq -r '.result[].SubscriberPackageVersionId)' <<< "$pkg_create_report")
        echo "sub-pkg-ver-id=$final_variable" >> "$GITHUB_OUTPUT"

        echo "$final_variable"
