overrides:
  - files:
      - .github/actions/*/action.yaml
      - .github/actions/*/action.yml
      - .github/workflows/*.yaml
      - .github/workflows/*.yml
    options:
      singleQuote: true
      endOfLine: lf
      semi: false
      parser: babel
      useTabs: false
      bracketSpacing: false
  - files: "**/*.json"
    options:
      tabWidth: 2
