semi: false
overrides:
  - files:
      - ".github/workflows/*.yml"
      - ".github/actions/*/action.yml"
      - ".github/workflows/*.yaml"
      - ".github/actions/*/action.yaml"
    options:
      singleQuote: true
  - files:
      - "**/*.json"
    options:
      tabWidth: 2
