overrides:
  - files:
      - .github/actions/*/action.yaml
      - .github/actions/*/action.yml
      - .github/workflows/*.yaml
      - .github/workflows/*.yml
    options:
      singleQuote: true
  - files: "**/*.json"
    options:
      tabWidth: 2
