name: Prettier Check
description: 'A action which runs the Prettier CLI Check'
inputs:
  prettier-version:
    description: 'The version of prettier to install'
    required: false
    default: '3.1.1'
  fail_on_error:
    description: 'Whether the script should fail when linting errors are found'
    required: false
    default: true
  files-to-check:
    description: 'Files to check'
    required: false
    default: '**/*'
runs:
  using: composite
  steps:
    - name: Install Prettier through NPM
      id: prettier-install
      shell: bash
      run: npm install --global prettier@${{ inputs.prettier-version }}
    - name: Run Prettier
      id: prettier-run
      env: 
        FILES_TO_CHECK: ${{ inputs.files-to-check }}
      shell: bash
      run: |
        prettier_output="$(
        prettier --list-different \
        --config .prettierrc.yml \
        --ignore-unknown \
        --no-error-on-unmatched-pattern \
        $FILES_TO_CHECK)" \
        || ( 
        IFS=$'\n'   # Set the Internal Field Separator to newline
        for file_to_prettify in $prettier_output; do
          echo "::error:: File to Prettify: $file_to_prettify"
        done        
        echo "::notice:: Follow bellow steps to prettify your code:%0A- Install prettier locally: https://prettier.io/docs/en/install.html%0A- Then format all filles with this command: prettier FILE_NAME --write"
        exit 1
        )
