name: Prettier Check
description: 'A simple action which runs the Prettier CLI Check'
inputs:
  prettier_version:
    description: 'The version of prettier to install'
    required: false
    default: 'latest'
  fail_on_error:
    description: 'Whether the script should fail when linting errors are found'
    required: false
    default: true
  file_pattern:
    description: 'The file pattern to scan'
    required: false
    default: '**/*'
outputs:
  PRETTIER_OUTPUT:
    description: 'The output from prettier'
    value: ${{ steps.prettier-run.outputs.prettier-output }}
runs:
  using: 'composite'
  steps:
    - name: Installing Prettier
      id: prettier-install
      shell: bash
      run: npm install --global prettier@${{ inputs.prettier_version }}
    - name: Running Prettier
      id: prettier-run
      shell: bash
      run: |
        echo prettier_output<<EOF
        prettier --list-different --config .prettierrc.yml --ignore-unknown --no-error-on-unmatched-pattern ${{ inputs.file_pattern }}
        EOF
        echo "PRETTIER_OUTPUT=$prettier_output" >> "$GITHUB_OUTPUT"
    - name: Fail On Error
      id: fail-on-error
      if:  steps.prettier-run.outputs.PRETTIER_OUTPUT != '' && inputs.fail_on_error
      shell: bash
      run: |
        echo ""
        echo "Follow bellow steps to prettify your code:"
        echo "Install prettier locally: https://prettier.io/docs/en/install.html"
        echo "Then format all filles with this command: prettier FILE_NAME --write"
        exit 1
