name: Prettier Check
description: 'A simple action which runs the Prettier CLI Check'
inputs:
  config_path:
    description: 'The path to the prettierrc file'
    required: false
    default: ''
  prettier_version:
    description: 'The version of prettier to install'
    required: false
    default: 'latest'
  fail_on_error:
    description: 'Whether the script should fail when linting errors are found'
    required: false
    default: true
outputs:
  prettier_output:
    description: 'The output from prettier'
    value: ${{ steps.prettier-run.outputs.prettier-output }}
runs:
  using: 'composite'
  steps:
    - name: Installing Prettier
      id: prettier-install
      shell: bash
      run: npm install --global prettier@${{ inputs.prettier_version }}
    - name: Running Prettier
      id: prettier-run
      shell: bash
      run: |
        mapfile -t my_array < <(git diff --name-only)
        for element in "${my_array[@]}"; do
          echo "prettier-output=$(prettier $element --config ${{ inputs.config_path }} --list-different --no-error-on-unmatched-pattern)"
        done
    - name: Fail On Error
      id: fail-on-error
      if: env.PRETTIER_OUTPUT != '' && inputs.fail_on_error
      shell: bash
      run: |
        echo "Follow bellow steps to prettify your code:"
        echo "Install prettier locally: https://prettier.io/docs/en/install.html"
        echo "Then format all filles with this command: prettier FILE_NAME --write"
        exit 1
