name: Check Folder Changes

on:
  pull_request:
    paths:
      - '*/objects/*/fields/*'

jobs:
  check_changes:
    name: Check Folder Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: List new files
        run: |
          echo "${{ github.event.pull_request.head.sha }}"
          echo "${{ github.event.pull_request.base.sha }}"
          git rev-list --max-parents=0 HEAD
          git diff --name-status origin/main 
          new_files=$(git diff --name-status origin/main...HEAD | grep -E '^A' | grep '*/objects/*/fields/')
          if [ -n "$new_files" ]; then
            echo "nice"
          else
            echo "No new files in '*/objects/*/fields/' folder."
          fi
