# Action to create artifact
name: create-artifact
on:
  pull_request:
    branches:
      - main
jobs:
  create-arifact:
    concurrency: group
    name: Create Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: echo "test 0" > sampleFile.txt
      - name: Share file
        uses: actions/upload-artifact@v3
        with:
          name: authfiles
          path: ./sampleFile.txt

          
  # reusable_workflow:
  #   concurrency: group
  #   uses: ./.github/workflows/download-artifact.yml
  #   with: 
  #     workflow-run-number: ${{ github.run_number }}
  #     workflow-run-id: ${{ github.run_id }}
  #     commit-sha: ${{ github.sha }}
