name: Different dir different action
run-name: ${{ github.actor }} is testing out bash script 🌃
on:
    pull_request:
      branches:
        - main
      paths:
        - .github/workflows/different-dir-different-action.yml
        - force-app*/**
jobs:
  save-output:
    runs-on: ubuntu-latest
    steps: 
      - name: Create the Base Model Package
        run: echo "Create the base Model Package"  
      - name: Create the Framework Model Package
        run: echo "Create the Framework Model Package"  
  