name: Different dir different action
run-name: ${{ github.actor }} is testing out bash script 🌃
on:
    pull_request:
      branches:
        - main
      paths:
        - .github/workflows/different-dir-different-action.yml
        - force-app/base/*
        - force-app/framework/*
jobs:
  save-output:
    runs-on: ubuntu-latest
    steps: 
      - name: Create the Base Model Package
        if: ${{ github.event.pull_request.head.repo.full_name == TestGitHubActions && contains(github.event.pull_request.changed_files, 'force-app/base/*') }}
        run: echo "Create the base Model Package"  
      - name: Create the Framework Model Package
        if: contains(github.event.pull_request.changed_files, 'force-app/framework/*')
        run: echo "Create the Framework Model Package"  
  