name: Different dir different action
run-name: ${{ github.actor }} is testing out bash script 🌃
on:
  pull_request:
    branches:
      - main 
    paths:
      - .github/workflows/different-dir-different-action.yml
      - force-app/base/*
      - force-app/framework/*
jobs:
  save-output:
    runs-on: ubuntu-latest
    steps: 
      - name: Echo variables
        run: echo "github.head_ref = ${{ github.head_ref }} && github.base_ref = ${{ github.base_ref }}"
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - name: Save paths from changed files on pull request.
        run: |
          changed_files=$(git diff --name-only ${{ github.head_ref }} ${{ github.base_ref }})

          echo "Changed files:"
          echo "$changed_files"

          printf %s\\n \
            'CHANGED_FILES<<EOV' \
            "$changed_files" \
            EOV \
          >> "$GITHUB_ENV"
      - name: Create the Data Model Package
        id: create-data-model-pkg
        if: >-
          ((contains(env.CHANGED_FILES, 'force-app/base/')
          || contains(env.CHANGED_FILES, 'force-app/framework/'))
          && contains(env.CHANGED_FILES, 'force-app/data-model/') != true) != true
        run: echo "Data model"
      - name: Create the Framework Package
        id: create-framework-pkg
        if: >-
          (contains(env.CHANGED_FILES, 'force-app/base/')
          && contains(env.CHANGED_FILES, 'force-app/framework/') != true
          && contains(env.CHANGED_FILES, 'force-app/data-model/') != true) != true    
        run: echo "framework"
