name: Different dir different action
run-name: ${{ github.actor }} is testing out bash script 🌃
on:
    pull_request:
      branches:
        - main
      paths:
        - .github/workflows/different-dir-different-action.yml
        - force-app/base/*
        - force-app/framework/*
jobs:
  save-output:
    runs-on: ubuntu-latest
    steps: 
      - name: Echo variables
        run: echo "github.event.pull_request.head.repo.full_name = ${{ github.event.pull_request.head.repo.full_name }} && github.event.pull_request.changed_files = ${{ github.event.pull_request.changed_files }}"
      - name: Create the Base Model Package
        if: ${{ github.event.pull_request.head.repo.full_name == 'Kacper326/TestGitHubActions' && contains(github.event.pull_request.changed_files, 'force-app/base/*') }}
        run: echo "Create the base Model Package"  
      - name: Create the Framework Model Package
        if: contains(github.event.pull_request.changed_files, 'force-app/framework/*')
        run: echo "Create the Framework Model Package"  
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Fetch remote branches
        run: git fetch origin ${{ github.head_ref }}:${{ github.head_ref }} && git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
      - name: Process files changed in the current commit
        run: |
            for file in $changedFiles; do
              echo "Processing file: $file"
            done
            echo ${{ github.event.pull_request.commits }}
      - name: Check if there are changes in base
        run: 
          changedFiles=$(git diff --name-only ${{ github.head_ref }} ${{ github.base_ref }})
          
          echo "$changedFiles"
