name: Different dir different action
run-name: ${{ github.actor }} is testing out bash script 🌃
on:
    pull_request:
      branches:
        - main
      paths:
        - .github/workflows/different-dir-different-action.yml
        - force-app*/**
jobs:
  save-output:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps: 
      - id: step1
        run: echo "test=" >> "$GITHUB_OUTPUT"
  pass-and-print-output:
    runs-on: ubuntu-latest
    needs: save-output
    if: ${{ needs.save-output.outputs.output1 }}
    steps:
      - run: echo ${{ needs.save-output.outputs.output1 }}
  