name: Different dir different action
run-name: ${{ github.actor }} is testing out bash script 🌃
on:
    pull_request:
      branches:
        - main
      paths:
        - .github/workflows/different-dir-different-action.yml
        - force-app/base/*
        - force-app/framework/*
jobs:
  save-output:
    runs-on: ubuntu-latest
    steps: 
      - name: Create the Base Model Package
        if: ${{ github.event.pull_request.head.repo.full_name == 'Kacper326/TestGitHubActions' && contains(github.event.pull_request.changed_files, 'force-app/base/*') }}
        run: echo "Create the base Model Package"  
      - name: Create the Framework Model Package
        if: contains(github.event.pull_request.changed_files, 'force-app/framework/*')
        run: echo "Create the Framework Model Package"  
      - name: Checkout (fetch last two commits) of the PR
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: ${{ github.event.pull_request.commits }}
      - name: Process files changed in the current commit
        run: |
          changedFiles=$(git diff --name-only HEAD^)
          for file in $changedFiles; do
            echo "Processing file: $file"
          done
          echo ${{ github.event.pull_request.commits }}
  