name: download-artifact
on: 
  workflow_call:
jobs:
  echo-smth:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3

      - name: Write smth
        run: 
            echo "It works"