name: download-artifact
on: 
  workflow_call:
  push:
    branches:
      - main
      - develop
jobs:
  download-artifact:
    name: Download artifact 
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v3
      - name: Download-artifact
        id: download-artifact
        if: ${{ github.event_name != 'push' }} 
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: create-artifact.yml
          run_id: ${{ github.event.workflow_run.id }}
          if_no_artifact_found: fail
      - name: check
        run: |
          ls -l