name: download-artifact
on: 
  workflow_call:
jobs:
  echo-smth:
    runs-on: ubuntu-latest
    steps: 
      - name: check out
        uses: actions/checkout@v3
      - name: write smth
        run: echo "It works"