name: download-artifact
on: 
  workflow_dispatch:
jobs:
  download-artifact:
    name: Download artifact 
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v2
      - name: Write smth
        run: echo "It works"