name: download-artifact
on: 
  workflow_call:
jobs:
  download-artifact:
    name: Download artifact 
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v3
      - name: Write smth
        run: echo ${{ github.run_number }}
      - name: Download-artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: create-artifact.yml
          commit: ${{github.event.pull_request.head.sha}}
          if_no_artifact_found: fail
      - name: check
        run: |
          ls -l