name: download-artifact
on:
  # workflow_call:
  #   inputs:
  #     workflow-run-number:
  #       type: string
  #       required: true
  #       default: ''
  #       description: >-
  #         Workflow run number to download the proper artifact.
  #     workflow-run-id:
  #       type: string
  #       required: false
  #       default: ''
  #       description: >-
  #         Workflow run ID to download the proper artifact.
  #     commit-sha:
  #       type: string
  #       required: false
  #       default: ''
  #       description: >-
  #         Top commit SHA to download the proper artifact
  workflow_run:
    workflows:
      - create-artifact
    types:
      - completed
  # push:
  #   branches:
  #     - main
  #     - develop
jobs:
  download-artifact:
    name: Download artifact
    runs-on: ubuntu-latest
    steps:
      - name: Check if I can get sha of workflow webhook
        run: echo "github.event.workflow_run.pull_requests.head.sha:${{ github.event.workflow_run.pull_requests.base.sha }}"
      - name: Checkout on push event
        if: github.event_name == 'push'
        uses: actions/checkout@v3
      - name: Checkout on workflow run event
        if: github.event_name == 'workflow_run'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.pull_requests.base.sha }}
      - name: check inputs
        run: |
          echo "runner id: ${{ inputs.workflow-run-id }}"
          echo "runner number: ${{ inputs.workflow-run-number }}"
          echo "commit SHA: ${{ inputs.commit-sha }}"
          echo "workflow_run.id: ${{ github.event.workflow_run.id }}"
      - name: Download-artifact
        id: download-artifact
        if: ${{ github.event_name != 'push' }}
        uses: dawidd6/action-download-artifact@v2
        with:
          name: authfiles
          # run_id: ${{ inputs.workflow-run-id }}
          run_id: ${{ github.event.workflow_run.id }}
      - name: check
        run: |
          ls -l
          cat sampleFile.txt
