name: Continuous Integration
on:
  pull_request:
    branches: alskjgs
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          dry: true
          prettier_options: --check **/*.{json,yml,yaml} --no-error-on-unmatched-pattern
          only_changed: True
      - name: List out Unprettefied Files as warning
        shell: sh
        run: |
          git diff --name-only \
            | awk '{print "::warning files =" $0 "::File needs prerrifing." }'
