name: Ensure prettiness of the code base
on:
  pull_request:
    branches: main
jobs:
  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v41
      - name: Prettier Check
        uses: ./.github/actions/prettier-cli-action
        with:
          files_to_check: ${{ steps.changed-files.outputs.all_changed_files }}