name: Ensure prettiness of the code base
on:
  pull_request:
    branches: main
jobs:
  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          dry: true
          prettier_options: --check --no-error-on-unmatched-pattern ${{ steps.changed-files.outputs.all_changed_files }}
      - name: List out Unprettefied Files as warning
        shell: sh
        run: |
          git diff --name-only \
            | awk '{print "::warning files =" $0 "::File needs prerrifing." }'