name: Ensure prettiness of the code base
on:
  pull_request:
    branches: main
jobs:
  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup yq
        uses: dcarbone/install-yq-action@v1.1.1
        with:
          version: 'v4.35.1'
          download-compressed: 'true'
          force: 'false'
      - name: Check yq
        run: |
          which yq
          yq --version
      - name: Run Prettier
        id: prettier-run
        uses: ./.github/actions/prettier-cli-action
        with:
          config_path: .prettierrc.yml
      - name: Cat prettierrc.yml
        run: cat .prettierrc.yml
      - name: Prettier Output
        if: ${{ failure() }}
        shell: bash
        run: |
          echo "The following files are not formatted:"
          echo "${{ steps.prettier-run.outputs.prettier_output }}"
          echo "Follow bellow steps to prettify your code:"
          echo "Install prettier locally: https://prettier.io/docs/en/install.html"
          echo "Then format all filles with this command: prettier FILE_NAME --write"
