name: test output
run-name: ${{ github.actor }} is testing out bash script 🚀
on: 
  [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Codebase
        uses: actions/checkout@v3
      - name: Print Output
        id: print-output
        uses: ./.github/actions/output-test
      - name: Step to check if I can put in output
        if: steps.print-output.outputs.sub-pkg-ver-id
        run: echo ${{ steps.print-output.outputs.sub-pkg-ver-id }}