name: test output
run-name: ${{ github.actor }} is testing out bash script 🚀
on: 
  workflow_dispatch:
  pull_request:
    branch:
      - main
jobs:
  save-output:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps: 
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
  pass-and-print-outpur:
    runs-on: ubuntu-latest
    needs: save-output
    steps:
      - run: echo ${{needs.save-output.outputs.output1}}
  